---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ include "gnosis-bridge.fullname" . }}-redis
  labels:
    app.kubernetes.io/instance: gnosis-bridge
    app.kubernetes.io/name: gnosis-bridge
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
    {{- if .Values.redis.resources }}
    {{- with .Values.redis.resources }}
    resources:
      {{- toYaml . | nindent 12 }}
    {{- end }}
    {{- else }}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    {{- end }}
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard-rwo
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisConfig:
    additionalRedisConfig: {{ include "gnosis-bridge.fullname" . }}-redis
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5